sonar.projectKey=ammaramrcan-ops_nafath
sonar.organization=ammaramrcan-ops
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx
sonar.typescript.lcov.reportPaths=coverage/lcov.info
